version: '3'

services:
  commander:
    build:
      context: .
      dockerfile: ./commander/Dockerfile
    container_name: commander_con
    volumes:
      - ./commander:/app
    ports:
      - 5000:5000
    networks:
      - case1-network

  general1:
    build:
      context: .
      dockerfile: ./general1/Dockerfile
    container_name: general1_con
    volumes:
      - ./general1:/app
    ports:
      - 5001:5001
    networks:
      - case1-network

  general2:
    build:
      context: .
      dockerfile: ./general2/Dockerfile
    container_name: general2_con
    volumes:
      - ./general2:/app
    ports:
      - 5002:5002
    networks:
      - case1-network

  general3:
    build:
      context: .
      dockerfile: ./general3/Dockerfile
    container_name: general3_con
    volumes:
      - ./general3:/app
    ports:
      - 5003:5003
    networks:
      - case1-network

networks:
  case1-network:
    external: true